alias r := run
alias w := watch
alias e := example
alias we := watch-example

_default:
    @just --list

run day *args:
    if [ {{day}} -ge 7 ]; then \
        cmake --build --preset local-release --target {{day}} && \
        ./builds/local/Release/{{day}} ./inputs/{{trim_start_match(day, "0")}}; \
    else \
        uiua run --no-format {{args}} {{day}}.ua ./inputs/{{trim_start_match(day, "0")}}; \
    fi

watch day:
    if [ {{day}} -ge 7 ]; then \
        echo "{{day}}.cpp" | entr -c sh -c ' \
        cmake --build --preset local-release --target {{day}} && \
        ./builds/local/Release/{{day}} ./inputs/{{trim_start_match(day, "0")}}; \
        '; \
    else \
        uiua watch --no-format {{day}}.ua ./inputs/{{trim_start_match(day, "0")}}; \
    fi

example day ex:
    if [ {{day}} -ge 7 ]; then \
        cmake --build --preset local-release --target {{day}} && \
        ./builds/local/Release/{{day}} ./examples/{{day}}/{{ex}}; \
    else \
        uiua run --no-format {{day}}.ua ./examples/{{day}}/{{ex}}; \
    fi

watch-example day ex:
    if [ {{day}} -ge 7 ]; then \
        echo "{{day}}.cpp" | entr -c sh -c ' \
        cmake --build --preset local-release --target {{day}} && \
        ./builds/local/Release/{{day}} ./examples/{{day}}/{{ex}}; \
        '; \
    else \
        uiua watch --no-format {{day}}.ua ./examples/{{day}}/{{ex}}; \
    fi
