[package]
name = "task"
version = "0.1.0"
edition = "2021"

[dependencies]
genawaiter = "0.2"
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0", features = ["full"] }

[lib]
name = "task"
path = "src/task.rs"
proc-macro = true
